### ISSUE TITLE
"is not a function" errors

### ISSUE THREAD

**Issue by once-ler** [halt-hammerzeit/web-service#1]
Thanks for this brilliant project.

I encountered some errors trying to start a service.  Found the missing definitions in your other repo `__webapp__.  Specifically, __language.js__

Will you be including language.js to the __web-service__ repo?

In my entry.js, I added the following to get my app going:

```javascript
global._development_ = true;
global.log = { error: console.error };

// https://github.com/halt-hammerzeit/webapp/blob/master/code/common/language.js#L253
Object.defineProperty(Array.prototype, 'is_empty', 
{
  enumerable: false,
  value: function() { 
    return this.length == 0 
  }
});

// https://github.com/halt-hammerzeit/webapp/blob/master/code/common/language.js#L347
Object.defineProperty(String.prototype, 'ends_with', {
  enumerable: false,
  value: function(substring) {
    let i = this.length
    let j = substring.length

    if (j > i) {
      return false
    }

    while (j > 0) {
      i--
      j--

      if (this[i] !== substring[j]) {
        return false
      }
    }

    return true
  }
});

// https://github.com/halt-hammerzeit/webapp/blob/master/code/common/language.js#L3
var exists = what => typeof what !== 'undefined';
global.exists = exists;
```

**Comment by halt-hammerzeit** [comment]
Wow, thanks )

Sure, i'll fix the bugs you found, that helps.
I guess it will take about 10 minutes.

**Comment by halt-hammerzeit** [comment]
@once-ler Okay, I seem to have fixed all the bugs you've found so far. Try `npm install web-service@latest` and tell me if it works for you now.

**Comment by once-ler** [comment]
@halt-hammerzeit Thanks for (super) quick response.  
Works out of the box with ```web-service@latest```
