### ISSUE TITLE
It would be great to be able to decorate an existing koa server

### ISSUE THREAD

**Issue by Vincz** [halt-hammerzeit/web-service#3]
It would be great to allow passing a existing koa instance to the web_service() function.
This way, we could "decorate" an existing server with all your handy utilities.
Something like : 

```
import webservice from 'web-service'
import koa from 'koa';

const server = koa();
const service = webservice(server, { routing: true })
```

I'm running into this "issue" cause i based my project on your webpack-react-redux-isomorphic-render-example but i don't want to split the web server and the page server. The problem is that the webpage_server function from react-isomorphic-render already return an instance of koa. Instance i'd like to decorate with your webservice stuff :)

**Comment by halt-hammerzeit** [comment]
There's a possibility of running `react-isomorphic-render` as a middleware.
https://github.com/halt-hammerzeit/react-isomorphic-render#without-proxying
```js
import { render } from 'react-isomorphic-render/server'

try
{
  // Returns a Promise.
  //
  // status  - HTTP response status
  // content - rendered HTML document (markup)
  // redirect - redirection URL (in case of HTTP redirect)
  //
  const { status, content, redirect } = await render
  ({
    // Takes the same parameters as webpage server
    application: { host, port },
    assets,

    // Original HTTP request, which is used for
    // getting URL, cloning cookies, and inside `preload`.
    request,

    // The rest optional parameters are the same
    // as for webpage server and are all optional
  },
  // The second `settings` parameter is the same as for webpage server
  settings)

  if (redirect)
  {
    return request.redirect(redirect)
  }

  response.status(status || 200)
  response.send(content)
}
catch (error)
{
  response.status(500)
  response.send('Internal server error')
}
```

You can `.use()` this code before calling `.listen()` on a `webservice`.

```js
import { render } from 'react-isomorphic-render/server'

const webservice = ...
webservice.use(async (ctx, next) =>
{
  const request = ctx.request
  const response = ctx.response

  try
  {
    // Returns a Promise.
    //
    // status  - HTTP response status
    // content - rendered HTML document (markup)
    // redirect - redirection URL (in case of HTTP redirect)
    //
    const { status, content, redirect } = await render
    ({
      // Takes the same parameters as webpage server
      application: { host, port },
      assets,

      // Original HTTP request, which is used for
      // getting URL, cloning cookies, and inside `preload`.
      request,

      // The rest optional parameters are the same
      // as for webpage server and are all optional
    },
    // The second `settings` parameter is the same as for webpage server
    settings)

    if (redirect)
    {
      return request.redirect(redirect)
    }

    response.status(status || 200)
    response.send(content)
  }
  catch (error)
  {
    response.status(500)
    response.send('Internal server error')
  }

  // no need for `next()` because it returns HTTP response anyway
})
```

Did you get it?

**Comment by Vincz** [comment]
Ok i get it ! But there is still kind of a bug. When using the render function directly, as your example suggest, the render settings parameter is not the same as for the web page server because in the render function the options are not normalized. The missing part is :

    	common = normalize_common_options(common)

So we get exception like create_routes is not a function or other related errors dues to the fact that settings are not normalized.It'd be great if the settings parameters would be handle the same way by webpage server and by the render method itself.

**Comment by halt-hammerzeit** [comment]
Oh, missed that one.
Try the new version, it should be fixed.
